name: Maven TestNG CI Pipeline

# Trigger this workflow on push or pull requests to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 11 (as specified in your pom.xml)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Step 3: Install Google Chrome
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Step 4: Install ChromeDriver based on the detected Chrome version
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        echo "Detected Chrome version: $CHROME_VERSION"
        
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          echo "Could not determine ChromeDriver version for Chrome $CHROME_VERSION."
          exit 1
        fi
        echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    # Step 5: Run tests with Maven in headless mode using xvfb (X Virtual Framebuffer)
    - name: Run Maven tests with TestNG in headless mode
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' mvn clean test

    # Step 6: Upload test report as an artifact for review
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: target/surefire-reports/

    # Step 7: Display test results in the GitHub Actions logs
    - name: Show test results
      if: always()
      run: |
        cat target/surefire-reports/*.xml
