name: Maven TestNG CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y \
          xvfb \
          libxss1 \
          libappindicator1 \
          libindicator7 \
          fonts-liberation \
          libnss3 \
          lsb-release \
          xdg-utils \
          libx11-xcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libasound2 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libx11-6

    - name: Install ChromeDriver
      run: |
        # Detect Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        echo "Detected Chrome version: $CHROME_VERSION"
        
        # Fetch the correct ChromeDriver version
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          echo "Could not determine ChromeDriver version for Chrome $CHROME_VERSION. Please check the compatibility."
          exit 1
        fi
        echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        # Remove old ChromeDriver if it exists
        sudo rm -f /usr/local/bin/chromedriver
        
        # Download and install the correct ChromeDriver version
        wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run tests with Maven
      run: |
        # Run Maven tests with xvfb to provide a virtual display for Chrome
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' mvn clean test

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: target/surefire-reports/
